"""empty message

Revision ID: 20b6eb3e6562
Revises: 40c03cf9c8c0
Create Date: 2021-07-31 15:26:11.993390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20b6eb3e6562'
down_revision = '40c03cf9c8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.drop_table('artist')
    # op.drop_table('venue')
    # op.drop_table('show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('venue_fk1', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('artist_fk2', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['artist_fk2'], ['artist.id'], name='show_artist_fk2_fkey'),
                    sa.ForeignKeyConstraint(['venue_fk1'], ['venue.id'], name='show_venue_fk1_fkey'),
                    sa.PrimaryKeyConstraint('id', name='show_pkey')
                    )
    op.create_table('venue',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
                    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
                    sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
                    sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
                    sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
                    sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
                    sa.Column('website_link', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
                    sa.Column('seeking_description', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('genres', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='venue_pkey')
                    )
    op.create_table('artist',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
                    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
                    sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
                    sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
                    sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
                    sa.Column('website_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
                    sa.Column('seeking_description', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('seeking_venues', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('genres', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='artist_pkey')
                    )
    # ### end Alembic commands ###
