"""empty message

Revision ID: 398911ab742e
Revises: e79f7ad2d5f6
Create Date: 2021-07-30 00:20:44.454557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '398911ab742e'
down_revision = 'e79f7ad2d5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
