"""empty message

Revision ID: 3f1845b2e2b1
Revises: 9a69200a6889
Create Date: 2021-07-29 15:44:38.333111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f1845b2e2b1'
down_revision = '9a69200a6889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_fk1', sa.Integer(), nullable=False),
    sa.Column('artist_fk2', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_fk2'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venue_fk1'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Show_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('venue_fk1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('artist_fk2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_fk2'], ['artist.id'], name='Show_artist_fk2_fkey'),
    sa.ForeignKeyConstraint(['venue_fk1'], ['venue.id'], name='Show_venue_fk1_fkey'),
    sa.PrimaryKeyConstraint('id', name='Show_pkey')
    )
    op.drop_table('show')
    # ### end Alembic commands ###
