"""empty message

Revision ID: 48b3aca8c57a
Revises: b9fd346a0eaf
Create Date: 2021-07-24 19:41:15.213509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b3aca8c57a'
down_revision = 'b9fd346a0eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
