"""Delete unique constraint on both models (Artist & Venue)

Revision ID: e79f7ad2d5f6
Revises: 3f1845b2e2b1
Create Date: 2021-07-30 00:13:38.773341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79f7ad2d5f6'
down_revision = '3f1845b2e2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_facebook_link_key', 'artist', type_='unique')
    op.drop_constraint('artist_image_link_key', 'artist', type_='unique')
    op.drop_constraint('artist_website_link_key', 'artist', type_='unique')
    op.drop_constraint('venue_facebook_link_key', 'venue', type_='unique')
    op.drop_constraint('venue_image_link_key', 'venue', type_='unique')
    op.drop_constraint('venue_website_link_key', 'venue', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('venue_website_link_key', 'venue', ['website_link'])
    op.create_unique_constraint('venue_image_link_key', 'venue', ['image_link'])
    op.create_unique_constraint('venue_facebook_link_key', 'venue', ['facebook_link'])
    op.create_unique_constraint('artist_website_link_key', 'artist', ['website_link'])
    op.create_unique_constraint('artist_image_link_key', 'artist', ['image_link'])
    op.create_unique_constraint('artist_facebook_link_key', 'artist', ['facebook_link'])
    # ### end Alembic commands ###
